name: Deploy Serverless Service - bot

on:
  push:
    branches:
      - main
    paths:
        - "bot/**"
        - "md2tg/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SERVICE_PATH: bot
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Write credentials
      working-directory: ${{ env.SERVICE_PATH }}
      run: |
        printf "%s" '${{ secrets.SA_JSON_CREDENTIALS }}' > .yc
        printf "%s" '${{ secrets.YAPPA }}' > yappa.yaml
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Generate requirements.txt and install md2tg
      run: |
        uv pip install --system ./md2tg

    - name: Install Yappa
      working-directory: ${{ env.SERVICE_PATH }}
      run: |
        uv pip install --system yappa

    - name: Yappa Deploy
      working-directory: ${{ env.SERVICE_PATH }}
      run: |
        yappa deploy